services:
  - type: web
    name: todoapp
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PORT
        value: "8000"
      - key: BASE_URL
        value: "0.0.0.0"
      - key: SQLITE3_PATH
        value: "./data/todo.db"
